# Generated by Django 5.1.3 on 2024-11-30 07:47

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.upload_books_image),
        ),
    ]
