# Generated by Django 5.1.3 on 2024-11-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
